# DATA ANALYTICS

In [ ]:
#Required

#-->Python Basics
#-->maths : Differentiation, Integration, P&C
#-->Statistics : Mean, Median, Mode 

#-->Data is Everything and Vice Versa

In [ ]:
# 4 Libraries

#-->Numpy   
#-->Pandas
#-->Matplotlib
#-->Seaborn

In [ ]:
#1.NUMPY --> Numerical Python
#--> Array, Matrix
#--> Used in AI : OPEN CV (Computer Vision)      .Numpy and Pandas are Data Analysis Library

#2.PANDAS --> Panel Data

#3.Matplotlib --> Mathematical Plotting Library
#--> Pixels -- Rectangular Boxes -- 0 to 255     .Matplotlib and Seaborn are Data Visualization Library

#4.Seaborn --> Updated Version of Matplotlib

# Numpy

In [4]:
# Numpy is a general-purpose array-processing package. It provides a high-performance multidimensional array object,
# and tools for working with these arrays. It is the fundamental package for scientific computing with Python.
# Besides its obvious scientific uses, Numpy can also be used as an efficient multi-dimensional container of generic data



In [ ]:
# 1-D array

import numpy as np
arr1 = np.array([1,2,3,4])
arr1

In [2]:
#type of array

type(arr1)

numpy.ndarray

In [3]:
#dimension of array

arr1.ndim

1

In [9]:
# 2-D Array

arr2 = np.array([[23,56,89],[56,34,25]])
arr2.ndim    #Dimension of Array

2

In [7]:
arr2     #Matrix Form

array([[23, 56, 89],
       [56, 34, 25]])

In [18]:
# Shape & Size

arr2.shape

(2, 3)

In [19]:
arr2.size

6

In [12]:
# 3-D Array

arr3 = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
arr3

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [13]:
arr3.ndim  #Dimension 

3

In [20]:
# Shape & Size

arr3.shape

(1, 3, 3)

In [21]:
arr3.size

9

In [14]:
#WAP to slice the data 5 from arr3

arr3[0][1][1]

5

In [22]:
arr3[0][0][0]

1

In [23]:
arr3[0][2]

array([7, 8, 9])

In [16]:
#WAP to find the max. im arr3

arr3.max()

9

In [17]:
#$WAP to find the min. in arr3

arr3.min()

1