In [1]:
# WAP to find the common element in a List
L1 = [1,2,3,4,5]
L2 = [2,4,6,8,5]
for i in L1:
    for j in L2:
        if(i==j):
            print("common element is ", i)
else:
    print(-1)

common element is  2
common element is  4
common element is  5
-1


In [4]:
# WAP to find common element in a list using functiona
a = [1,2,3,4,5]
b = [2,4,6,8,5]

def common(a,b):
    for i in a:
        for j in b:
            if(i==j):
                print("common element is ", i)
            else:
                print(-1)

In [5]:
common(a,b)

-1
-1
-1
-1
-1
common element is  2
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
common element is  4
-1
-1
-1
-1
-1
-1
-1
common element is  5


In [6]:
#WAP to make an of 2 by 3
import numpy as np
arr1 = np.array([[1,2,3],[4,5,6]])
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
arr1.size

6

In [8]:
arr1.shape

(2, 3)

In [9]:
#WAP to make an array of 3 by 2
arr2 = np.array([[[1,2],[3,4],[5,6]]])
arr2

array([[[1, 2],
        [3, 4],
        [5, 6]]])

In [10]:
arr2.size

6

In [11]:
arr2.shape

(1, 3, 2)

In [12]:
#Array using String

a = np.array([1,2,"Python"])
a

array(['1', '2', 'Python'], dtype='<U11')

In [13]:
a.shape

(3,)

In [14]:
a.size

3

In [15]:
type(a)

numpy.ndarray

#  Zeros and Ones

In [ ]:
#ZEROS
#Syntax : np.zeros(shape)

In [16]:
np.zeros(0)     #Output as float

array([], dtype=float64)

In [17]:
np.zeros(3)     #Output as float

array([0., 0., 0.])

In [19]:
np.zeros([4,2])  #Output as float

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [20]:
np.zeros([10,20])    #Shape in list

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.]])

In [21]:
np.zeros((5), dtype=int)        #Output as integer

array([0, 0, 0, 0, 0])

In [22]:
 np.zeros([10,20], dtype=int)   #Output as integer

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [51]:
#Wap to make 3-D Martrix using zeros

z = np.zeros([5,3,3])      #Float

In [52]:
z

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [53]:
z.shape

(5, 3, 3)

In [54]:
z.size

45

In [55]:
z.ndim

3

In [56]:
y = np.zeros([5,3,3], dtype=int)
y

array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]])

In [44]:
y.shape

(5, 3, 3)

In [45]:
y.size

45

In [46]:
y.ndim

3

In [47]:
#Ones
#syntax : np.ones(shape)

m = np.ones(0)  #Float

In [48]:
m

array([], dtype=float64)

In [49]:
n = np.ones(2)    #Float
n

array([1., 1.])

In [50]:
n.size

2

In [38]:
n.shape

(2,)

In [39]:
n = np.ones([3], dtype=int)
n

array([1, 1, 1])

In [62]:
n = np.ones([5,6])
n

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [63]:
n.shape

(5, 6)

In [64]:
n.size

30

In [65]:
#WAP to make 3-D matrix of ones
n = np.ones([1,3,3], dtype=int)
n

array([[[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]]])

In [41]:
n.shape

(1, 3, 3)

In [42]:
n.size

9

In [57]:
n = np.ones([5,3,3])    #Float
n

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [59]:
n.shape

(5, 3, 3)

In [60]:
n.size

45

In [61]:
n = np.ones([5,3,3], dtype=int)    #Integer
n

array([[[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]]])

In [66]:
#WAP to make  a data of ones 5 by 6 with the help of tuple

x = np.ones((5,6))
x

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [67]:
x.shape

(5, 6)

In [68]:
x.size

30

# Arange function

In [69]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [70]:
x = np.arange(0)
x

array([], dtype=int32)

In [71]:
x = np.arange(2,20)
x

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [72]:
x = np.arange(50,2,-1)
x

array([50, 49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34,
       33, 32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17,
       16, 15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3])

# Empty Function

In [73]:
#No specific value , function create random data
x = np.empty(49)
x

array([1.10161888e-311, 1.10158752e-311, 4.54119474e-312, 0.00000000e+000,
       1.69484279e-319, 4.54119473e-312, 0.00000000e+000, 1.10162033e-311,
       0.00000000e+000, 0.00000000e+000, 0.00000000e+000, 1.10162065e-311,
       0.00000000e+000, 2.47032823e-323, 6.95185895e-310, 2.02369289e-320,
       2.47032823e-323, 6.95185895e-310, 9.88131292e-324, 0.00000000e+000,
       0.00000000e+000, 1.29516345e-318, 0.00000000e+000,             nan,
       0.00000000e+000, 3.56043053e-307, 1.60219306e-306, 7.56571288e-307,
       1.89146896e-307, 1.37961302e-306, 1.05699242e-307, 8.01097889e-307,
       1.78020169e-306, 7.56601165e-307, 1.02359984e-306, 1.33510679e-306,
       2.22522597e-306, 1.33511018e-306, 6.23057689e-307, 1.86921279e-306,
       8.90098127e-307, 1.78020848e-306, 1.60219035e-306, 1.42418172e-306,
       2.04712906e-306, 7.56589622e-307, 1.11258277e-307, 8.90111708e-307,
       0.00000000e+000])

In [74]:
x = np.empty((6,4))
x

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [76]:
x = np.empty((50,20))
x

array([[1.10162028e-311, 1.10162031e-311, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00

In [77]:
#Identity Matrix
x = np.identity(2)   #only one argument  #float
x

array([[1., 0.],
       [0., 1.]])

In [80]:
x = np.identity((10), dtype=int)    #integer
x

array([[1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1]])

In [101]:
x = np.identity(20)
x

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.

In [94]:
#Transpose Matrix
#WAP to create a matrix of 3x3

a = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
a

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [95]:
a.T        #For TRANSPOSE of matrix a

array([[[1],
        [4],
        [7]],

       [[2],
        [5],
        [8]],

       [[3],
        [6],
        [9]]])

In [96]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [97]:
a.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [108]:
#LINSPACE

z = np.linspace(5,2)    #Arguments NOT in LIST form
z

array([5.        , 4.93877551, 4.87755102, 4.81632653, 4.75510204,
       4.69387755, 4.63265306, 4.57142857, 4.51020408, 4.44897959,
       4.3877551 , 4.32653061, 4.26530612, 4.20408163, 4.14285714,
       4.08163265, 4.02040816, 3.95918367, 3.89795918, 3.83673469,
       3.7755102 , 3.71428571, 3.65306122, 3.59183673, 3.53061224,
       3.46938776, 3.40816327, 3.34693878, 3.28571429, 3.2244898 ,
       3.16326531, 3.10204082, 3.04081633, 2.97959184, 2.91836735,
       2.85714286, 2.79591837, 2.73469388, 2.67346939, 2.6122449 ,
       2.55102041, 2.48979592, 2.42857143, 2.36734694, 2.30612245,
       2.24489796, 2.18367347, 2.12244898, 2.06122449, 2.        ])

In [109]:
z = np.linspace(20,30)
z

array([20.        , 20.20408163, 20.40816327, 20.6122449 , 20.81632653,
       21.02040816, 21.2244898 , 21.42857143, 21.63265306, 21.83673469,
       22.04081633, 22.24489796, 22.44897959, 22.65306122, 22.85714286,
       23.06122449, 23.26530612, 23.46938776, 23.67346939, 23.87755102,
       24.08163265, 24.28571429, 24.48979592, 24.69387755, 24.89795918,
       25.10204082, 25.30612245, 25.51020408, 25.71428571, 25.91836735,
       26.12244898, 26.32653061, 26.53061224, 26.73469388, 26.93877551,
       27.14285714, 27.34693878, 27.55102041, 27.75510204, 27.95918367,
       28.16326531, 28.36734694, 28.57142857, 28.7755102 , 28.97959184,
       29.18367347, 29.3877551 , 29.59183673, 29.79591837, 30.        ])

In [110]:
z = np.linspace(30,20)
z

array([30.        , 29.79591837, 29.59183673, 29.3877551 , 29.18367347,
       28.97959184, 28.7755102 , 28.57142857, 28.36734694, 28.16326531,
       27.95918367, 27.75510204, 27.55102041, 27.34693878, 27.14285714,
       26.93877551, 26.73469388, 26.53061224, 26.32653061, 26.12244898,
       25.91836735, 25.71428571, 25.51020408, 25.30612245, 25.10204082,
       24.89795918, 24.69387755, 24.48979592, 24.28571429, 24.08163265,
       23.87755102, 23.67346939, 23.46938776, 23.26530612, 23.06122449,
       22.85714286, 22.65306122, 22.44897959, 22.24489796, 22.04081633,
       21.83673469, 21.63265306, 21.42857143, 21.2244898 , 21.02040816,
       20.81632653, 20.6122449 , 20.40816327, 20.20408163, 20.        ])

In [111]:
#Axis Line (0 = column, 1 = Row)
#WAP to add all the elements of matrix a, all the elements of row amd column
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
a.sum()

45

In [112]:
a.sum(axis=0)   #for row

array([12, 15, 18])

In [100]:
a.sum(axis=1)   #for column

array([ 6, 15, 24])