In [3]:
import numpy as np

In [4]:
#WAP to calculate the sum of 3 by 2 matrix wrt col wise and row wise

arr = np.array([[1,2],[3,4],[4,5]])

In [5]:
arr

array([[1, 2],
       [3, 4],
       [4, 5]])

In [7]:
arr.shape

(3, 2)

In [9]:
arr.sum()

19

In [10]:
#Col
arr.sum(axis=0)

array([ 8, 11])

In [11]:
#Row
arr.sum(axis=1)

array([3, 7, 9])

# Min, Max, Sort

In [14]:
# min --> gives the min. value
# max --> gives the max. values
# sort --> sort the array from small values to large values

In [12]:
arr1 = np.array([[23,45],[34,76],[78,32]])

In [15]:
arr1

array([[23, 45],
       [34, 76],
       [78, 32]])

In [18]:
#min.
arr1.min()

23

In [19]:
#max
arr1.max()

78

In [24]:
#sort
arr1.sort()

In [25]:
arr1

array([[23, 45],
       [34, 76],
       [32, 78]])

# Argmin, Argmax, Argsort

In [ ]:
#arg min. --> gives the min. values in form of index value
#arg max. --> gives the max. value in form of index value
#arg sort. --> sort the array in form of index values

In [27]:
arr2 = np.array([[26,46],[39,74],[72,35]])

In [28]:
arr2

array([[26, 46],
       [39, 74],
       [72, 35]])

In [29]:
#argmin
arr2.argmin()      # the index value of smaller number 26 is 0

0

In [30]:
#argmax 
arr2.argmax()     # the index value of biggest number 74 is 3

3

In [31]:
#argsort
arr2.argsort()    

array([[0, 1],
       [0, 1],
       [1, 0]], dtype=int64)